export const queryWorkloads = nodes => [
  ['point_lookup', 'MATCH (n:Node) WHERE n.value = 42 RETURN n.value LIMIT 1', 1, 42],
  ['range_count', 'MATCH (n:Node) WHERE n.value >= 400 AND n.value < 600 RETURN count(n)', 1,
    Math.floor(nodes / 1000) * 200 + Math.max(0, Math.min(200, nodes % 1000 - 400))],
  ['projection', 'MATCH (n:Node) RETURN n.value LIMIT 1000', Math.min(nodes, 1000)],
  ['one_hop', 'MATCH (n:Node)-[:R]->(m) WHERE n.value = 42 RETURN count(m)', 1,
    Math.floor((nodes - 43) / 1000) * 4 + 4],
  ['two_hop', 'MATCH (n:Node)-[:R]->()-[:R]->(m) WHERE n.value = 42 RETURN count(m)', 1],
  ['variable_1_3', 'MATCH (n:Node)-[:R*1..3]->(m) WHERE n.value = 42 RETURN count(DISTINCT m)', 1],
  ['count_nodes', 'MATCH (n:Node) RETURN count(n)', 1, nodes],
  ['count_edges', 'MATCH ()-[r:R]->() RETURN count(r)', 1, nodes * 4],
  ['sum', 'MATCH (n:Node) RETURN sum(n.value)', 1,
    Math.floor(nodes / 1000) * 499500 + (nodes % 1000) * (nodes % 1000 - 1) / 2],
  ['avg', 'MATCH (n:Node) RETURN avg(n.value)', 1],
  ['min_max', 'MATCH (n:Node) RETURN min(n.value), max(n.value)', 1, 0],
  ['group_count', 'MATCH (n:Node) RETURN n.bucket, count(*)', 64],
  ['distinct', 'MATCH (n:Node) RETURN count(DISTINCT n.bucket)', 1, 64],
  ['top_k', 'MATCH (n:Node) RETURN n.value ORDER BY n.value DESC LIMIT 10', 10],
  ['adaptive_degree', 'CALL graph.degree() YIELD node, degree RETURN count(*)', 1, nodes],
  ['adaptive_bfs', 'CALL graph.bfs(1) YIELD node, distance RETURN count(*)', 1, nodes],
  ['adaptive_dfs', 'CALL graph.dfs(1) YIELD node, order RETURN count(*)', 1, nodes],
  ['adaptive_shortest_path', `CALL graph.shortestpath(1, ${nodes}) YIELD path, cost RETURN count(*)`, 1, 1],
  ['adaptive_dijkstra', 'CALL graph.dijkstra(1) YIELD node, cost RETURN count(*)', 1, nodes],
  ['adaptive_wcc', 'CALL graph.wcc() YIELD node, component RETURN count(*)', 1, nodes],
  ['adaptive_scc', 'CALL graph.scc() YIELD node, component RETURN count(*)', 1, nodes],
  ['adaptive_pagerank', 'CALL graph.pagerank() YIELD node, score RETURN count(*)', 1, nodes],
  ['adaptive_triangle_count', 'CALL graph.trianglecount() YIELD triangleCount RETURN triangleCount', 1],
  ['adaptive_clustering', 'CALL graph.clusteringcoefficient() YIELD node, coefficient RETURN count(*)', 1, nodes],
  ['adaptive_k_core', 'CALL graph.kcore() YIELD node, core RETURN count(*)', 1, nodes],
  ['adaptive_louvain', 'CALL graph.louvain() YIELD node, community RETURN count(*)', 1, nodes],
  ['public_metadata', 'SHOW PROJECTS', 1],
  ['public_scalar_point', 'MATCH (n:Node) WHERE id(n) = 43 RETURN n.value', 1, 42],
]
